apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekasvr
          image: willwbowen/salonapi-eurekasvr
          ports:
            - containerPort: 8761
          env:
          - name: CONFIGSERVER_PORT
            value: 8888
          - name: CONFIGSERVER_URI
            value: "http://localhost:8888"
          - name: CONFIGSERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: configserver
                key: password
          - name: ENCRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: configserver
                key: encrypt-key
          - name: EUREKASERVER_PORT
            value: 8761
          - name: EUREKASERVER_URI
            value: "http://localhost:8761"
          - name: PROFILE
            value: "$PROFILE"
