apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eurekasvr-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekasvr
  template:
    metadata:
      labels:
        app: eurekasvr
    spec:
      containers:
        - name: eurekasvr
          image: willwbowen/salonapi-eurekasvr
          ports:
            - containerPort: $EUREKASERVER_PORT
          env:
          - name: CONFIGSERVER_PORT
            value: "$CONFIGSERVER_PORT"
          - name: CONFIGSERVER_PASSWORD
            value: "$CONFIGSERVER_PASSWORD"
          - name: ENCRYPT_KEY
            value: "$ENCRYPT_KEY"
          - name: EUREKASERVER_PORT
            value: "$EUREKASERVER_PORT"
          - name: EUREKASERVER_URI
            value: "$EUREKASERVER_URI"
          - name: PROFILE
            value: "$PROFILE"
