apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
spec:
  type: NodePort
  ports:
  - port: 8761
    nodePort: 30003
    protocol: TCP
  selector:
    app: eurekaserver
