apiVersion: v1
kind: Service
metadata:
  name: eurekasvr-service
  labels:
    app: eurekasvr
spec:
  type: NodePort
  ports:
  - port: $EUREKASERVER_PORT
    nodePort: 30002
    protocol: TCP
  selector:
    app: eurekasvr
